// clean-room; R3.3 requisition-to-pay and three-way match records.
'use strict';

export const migration = {
  id: '613_r3_procurement_core', dependsOn: ['612_r3_sales_core'],
  up(db) { db.exec(`
    CREATE TABLE IF NOT EXISTS purchase_requisition (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), requester_id TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'draft', needed_by TEXT, notes TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_requisition_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), requisition_id TEXT NOT NULL REFERENCES purchase_requisition(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, uom_id TEXT REFERENCES uom(id)) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_rfq (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), requisition_id TEXT REFERENCES purchase_requisition(id), supplier_id TEXT NOT NULL REFERENCES partner_master(id), state TEXT NOT NULL DEFAULT 'draft', currency TEXT NOT NULL DEFAULT 'IQD', response_due TEXT, idempotency_key TEXT UNIQUE, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_rfq_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), rfq_id TEXT NOT NULL REFERENCES purchase_rfq(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, unit_price REAL, lead_time_days INTEGER, selected INTEGER NOT NULL DEFAULT 0) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_order (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), supplier_id TEXT NOT NULL REFERENCES partner_master(id), rfq_id TEXT REFERENCES purchase_rfq(id), order_number TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'draft', currency TEXT NOT NULL DEFAULT 'IQD', total_amount REAL NOT NULL DEFAULT 0, idempotency_key TEXT UNIQUE, created_at TEXT NOT NULL, created_by TEXT) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_order_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), order_id TEXT NOT NULL REFERENCES purchase_order(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, received_qty REAL NOT NULL DEFAULT 0, billed_qty REAL NOT NULL DEFAULT 0, unit_price REAL NOT NULL, subtotal REAL NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_receipt (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), order_id TEXT NOT NULL REFERENCES purchase_order(id), stock_move_id TEXT REFERENCES stock_move(id), state TEXT NOT NULL DEFAULT 'draft', received_at TEXT, supplier_doc_ref TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_receipt_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), receipt_id TEXT NOT NULL REFERENCES purchase_receipt(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, accepted_qty REAL NOT NULL DEFAULT 0, rejected_qty REAL NOT NULL DEFAULT 0) STRICT;
    CREATE TABLE IF NOT EXISTS purchase_match (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), order_id TEXT NOT NULL REFERENCES purchase_order(id), receipt_id TEXT REFERENCES purchase_receipt(id), bill_id TEXT REFERENCES arap_document(id), qty_delta REAL NOT NULL DEFAULT 0, price_delta REAL NOT NULL DEFAULT 0, qty_tolerance REAL NOT NULL DEFAULT 0, price_tolerance REAL NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'pending', approved_by TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS supplier_scorecard (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), supplier_id TEXT NOT NULL REFERENCES partner_master(id), order_id TEXT REFERENCES purchase_order(id), on_time_score REAL NOT NULL DEFAULT 0, quality_score REAL NOT NULL DEFAULT 0, price_score REAL NOT NULL DEFAULT 0, notes TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_order_number ON purchase_order(company_id, order_number);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_receipt_supplier_doc ON purchase_receipt(company_id, supplier_doc_ref) WHERE supplier_doc_ref IS NOT NULL;
  `); },
  down(db) { db.exec('DROP TABLE IF EXISTS supplier_scorecard; DROP TABLE IF EXISTS purchase_match; DROP TABLE IF EXISTS purchase_receipt_line; DROP TABLE IF EXISTS purchase_receipt; DROP TABLE IF EXISTS purchase_order_line; DROP TABLE IF EXISTS purchase_order; DROP TABLE IF EXISTS purchase_rfq_line; DROP TABLE IF EXISTS purchase_rfq; DROP TABLE IF EXISTS purchase_requisition_line; DROP TABLE IF EXISTS purchase_requisition;'); }
};
