// clean-room; R3.4 warehouse operations, reservation, replenishment, and scan records.
'use strict';

export const migration = {
  id: '614_r3_inventory_operations', dependsOn: ['613_r3_procurement_core'],
  up(db) { db.exec(`
    CREATE TABLE IF NOT EXISTS stock_operation_type (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), code TEXT NOT NULL, name TEXT NOT NULL, sequence_code TEXT NOT NULL, picking_policy TEXT NOT NULL DEFAULT 'partial', active INTEGER NOT NULL DEFAULT 1) STRICT;
    CREATE TABLE IF NOT EXISTS stock_route (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1) STRICT;
    CREATE TABLE IF NOT EXISTS stock_route_rule (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), route_id TEXT NOT NULL REFERENCES stock_route(id) ON DELETE CASCADE, source_location_id TEXT REFERENCES locations(location_id), dest_location_id TEXT REFERENCES locations(location_id), operation_type_id TEXT REFERENCES stock_operation_type(id), sequence INTEGER NOT NULL DEFAULT 10, trigger_type TEXT NOT NULL DEFAULT 'pull', active INTEGER NOT NULL DEFAULT 1) STRICT;
    CREATE TABLE IF NOT EXISTS stock_reservation (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), product_id TEXT NOT NULL REFERENCES product_master(id), location_id TEXT NOT NULL REFERENCES locations(location_id), demand_ref TEXT NOT NULL, qty REAL NOT NULL CHECK(qty > 0), reserved_qty REAL NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'reserved', created_at TEXT NOT NULL) STRICT;
    CREATE UNIQUE INDEX IF NOT EXISTS idx_stock_reservation_ref ON stock_reservation(company_id, demand_ref, product_id, location_id);
    CREATE TABLE IF NOT EXISTS stock_pick (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), operation_type_id TEXT REFERENCES stock_operation_type(id), source_ref TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'draft', packed_at TEXT, shipped_at TEXT, created_at TEXT NOT NULL, created_by TEXT) STRICT;
    CREATE TABLE IF NOT EXISTS stock_pick_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), pick_id TEXT NOT NULL REFERENCES stock_pick(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), location_id TEXT REFERENCES locations(location_id), qty REAL NOT NULL, picked_qty REAL NOT NULL DEFAULT 0, packed_qty REAL NOT NULL DEFAULT 0, batch_number TEXT, serial_number TEXT) STRICT;
    CREATE TABLE IF NOT EXISTS stock_reorder_rule (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), product_id TEXT NOT NULL REFERENCES product_master(id), location_id TEXT NOT NULL REFERENCES locations(location_id), min_qty REAL NOT NULL DEFAULT 0, max_qty REAL NOT NULL DEFAULT 0, multiple_qty REAL NOT NULL DEFAULT 1, vendor_id TEXT REFERENCES partner_master(id), active INTEGER NOT NULL DEFAULT 1) STRICT;
    CREATE TABLE IF NOT EXISTS stock_cycle_count (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), location_id TEXT NOT NULL REFERENCES locations(location_id), state TEXT NOT NULL DEFAULT 'draft', count_date TEXT NOT NULL, approved_by TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS stock_cycle_count_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), count_id TEXT NOT NULL REFERENCES stock_cycle_count(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), expected_qty REAL NOT NULL DEFAULT 0, counted_qty REAL, variance REAL, adjustment_id TEXT REFERENCES stock_inventory_adjustment(id)) STRICT;
    CREATE TABLE IF NOT EXISTS stock_barcode_scan (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), barcode TEXT NOT NULL, product_id TEXT REFERENCES product_master(id), operation_id TEXT, scan_type TEXT NOT NULL, qty REAL NOT NULL DEFAULT 1, scanned_at TEXT NOT NULL, scanned_by TEXT) STRICT;
  `); },
  down(db) { db.exec('DROP TABLE IF EXISTS stock_barcode_scan; DROP TABLE IF EXISTS stock_cycle_count_line; DROP TABLE IF EXISTS stock_cycle_count; DROP TABLE IF EXISTS stock_reorder_rule; DROP TABLE IF EXISTS stock_pick_line; DROP TABLE IF EXISTS stock_pick; DROP TABLE IF EXISTS stock_reservation; DROP TABLE IF EXISTS stock_route_rule; DROP TABLE IF EXISTS stock_route; DROP TABLE IF EXISTS stock_operation_type;'); }
};
