// clean-room; R3.5 BOM, routing, work-order, and costing records.
'use strict';

export const migration = {
  id: '615_r3_manufacturing_core', dependsOn: ['614_r3_inventory_operations'],
  up(db) { db.exec(`
    CREATE TABLE IF NOT EXISTS mrp_bom (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), product_id TEXT NOT NULL REFERENCES product_master(id), code TEXT NOT NULL, revision TEXT NOT NULL DEFAULT 'A', bom_type TEXT NOT NULL DEFAULT 'normal', output_qty REAL NOT NULL DEFAULT 1, effective_from TEXT, effective_to TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, created_by TEXT) STRICT;
    CREATE UNIQUE INDEX IF NOT EXISTS idx_mrp_bom_revision ON mrp_bom(company_id, product_id, code, revision);
    CREATE TABLE IF NOT EXISTS mrp_bom_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), bom_id TEXT NOT NULL REFERENCES mrp_bom(id) ON DELETE CASCADE, component_product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, uom_id TEXT REFERENCES uom(id), scrap_pct REAL NOT NULL DEFAULT 0, phantom INTEGER NOT NULL DEFAULT 0, supplied_by_vendor INTEGER NOT NULL DEFAULT 0) STRICT;
    CREATE TABLE IF NOT EXISTS mrp_work_center (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), code TEXT NOT NULL, name TEXT NOT NULL, capacity REAL NOT NULL DEFAULT 1, hourly_cost REAL NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1) STRICT;
    CREATE TABLE IF NOT EXISTS mrp_routing_operation (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), bom_id TEXT NOT NULL REFERENCES mrp_bom(id) ON DELETE CASCADE, work_center_id TEXT NOT NULL REFERENCES mrp_work_center(id), sequence INTEGER NOT NULL, duration_minutes REAL NOT NULL DEFAULT 0) STRICT;
    CREATE TABLE IF NOT EXISTS mrp_work_order (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), bom_id TEXT NOT NULL REFERENCES mrp_bom(id), product_id TEXT NOT NULL REFERENCES product_master(id), order_number TEXT NOT NULL, qty REAL NOT NULL, state TEXT NOT NULL DEFAULT 'draft', planned_start TEXT, planned_end TEXT, actual_cost REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL, created_by TEXT) STRICT;
    CREATE TABLE IF NOT EXISTS mrp_work_order_component (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), work_order_id TEXT NOT NULL REFERENCES mrp_work_order(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), required_qty REAL NOT NULL, consumed_qty REAL NOT NULL DEFAULT 0, stock_move_id TEXT REFERENCES stock_move(id)) STRICT;
    CREATE TABLE IF NOT EXISTS mrp_scrap (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), work_order_id TEXT REFERENCES mrp_work_order(id), product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, reason TEXT NOT NULL, stock_move_id TEXT REFERENCES stock_move(id), created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS mrp_byproduct (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), bom_id TEXT NOT NULL REFERENCES mrp_bom(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, valuation_share REAL NOT NULL DEFAULT 0) STRICT;
    CREATE TABLE IF NOT EXISTS mrp_cost_rollup (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), work_order_id TEXT NOT NULL REFERENCES mrp_work_order(id), material_cost REAL NOT NULL DEFAULT 0, labor_cost REAL NOT NULL DEFAULT 0, overhead_cost REAL NOT NULL DEFAULT 0, total_cost REAL NOT NULL DEFAULT 0, computed_at TEXT NOT NULL) STRICT;
  `); },
  down(db) { db.exec('DROP TABLE IF EXISTS mrp_cost_rollup; DROP TABLE IF EXISTS mrp_byproduct; DROP TABLE IF EXISTS mrp_scrap; DROP TABLE IF EXISTS mrp_work_order_component; DROP TABLE IF EXISTS mrp_work_order; DROP TABLE IF EXISTS mrp_routing_operation; DROP TABLE IF EXISTS mrp_work_center; DROP TABLE IF EXISTS mrp_bom_line; DROP TABLE IF EXISTS mrp_bom;'); }
};
