// clean-room; R3.7 projects, separate project timesheets, helpdesk, SLA, and field service.
'use strict';

export const migration = {
  id: '617_r3_services_helpdesk', dependsOn: ['616_r3_landed_subcontracting'],
  up(db) { db.exec(`
    CREATE TABLE IF NOT EXISTS project_project (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), partner_id TEXT REFERENCES partner_master(id), name TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'active', billing_method TEXT NOT NULL DEFAULT 'time_materials', contract_value REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL, created_by TEXT) STRICT;
    CREATE TABLE IF NOT EXISTS project_phase (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), project_id TEXT NOT NULL REFERENCES project_project(id) ON DELETE CASCADE, name TEXT NOT NULL, sequence INTEGER NOT NULL DEFAULT 10, milestone_date TEXT, state TEXT NOT NULL DEFAULT 'open') STRICT;
    CREATE TABLE IF NOT EXISTS project_task (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), project_id TEXT NOT NULL REFERENCES project_project(id) ON DELETE CASCADE, phase_id TEXT REFERENCES project_phase(id), parent_id TEXT REFERENCES project_task(id), title TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'todo', assignee_id TEXT, planned_hours REAL NOT NULL DEFAULT 0, actual_hours REAL NOT NULL DEFAULT 0, due_date TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS project_task_dependency (task_id TEXT NOT NULL REFERENCES project_task(id) ON DELETE CASCADE, depends_on_task_id TEXT NOT NULL REFERENCES project_task(id), company_id TEXT NOT NULL REFERENCES companies(company_id), PRIMARY KEY(task_id, depends_on_task_id)) STRICT;
    CREATE TABLE IF NOT EXISTS project_milestone (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), project_id TEXT NOT NULL REFERENCES project_project(id) ON DELETE CASCADE, name TEXT NOT NULL, amount REAL NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'open', due_date TEXT) STRICT;
    CREATE TABLE IF NOT EXISTS project_timesheet (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), project_id TEXT NOT NULL REFERENCES project_project(id), task_id TEXT REFERENCES project_task(id), user_id TEXT NOT NULL, work_date TEXT NOT NULL, hours REAL NOT NULL CHECK(hours > 0), rate REAL NOT NULL DEFAULT 0, billable INTEGER NOT NULL DEFAULT 1, description TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS project_contract_line (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), project_id TEXT NOT NULL REFERENCES project_project(id), product_id TEXT REFERENCES product_master(id), description TEXT NOT NULL, qty REAL NOT NULL DEFAULT 1, unit_rate REAL NOT NULL DEFAULT 0, billing_rule TEXT NOT NULL DEFAULT 'time') STRICT;
    CREATE TABLE IF NOT EXISTS helpdesk_ticket (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), project_id TEXT REFERENCES project_project(id), partner_id TEXT REFERENCES partner_master(id), title TEXT NOT NULL, description TEXT, state TEXT NOT NULL DEFAULT 'open', priority TEXT NOT NULL DEFAULT 'normal', assignee_id TEXT, opened_at TEXT NOT NULL, closed_at TEXT) STRICT;
    CREATE TABLE IF NOT EXISTS helpdesk_sla (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), name TEXT NOT NULL, priority TEXT NOT NULL DEFAULT 'normal', response_hours REAL NOT NULL, resolution_hours REAL NOT NULL, active INTEGER NOT NULL DEFAULT 1) STRICT;
    CREATE TABLE IF NOT EXISTS helpdesk_ticket_sla (ticket_id TEXT NOT NULL REFERENCES helpdesk_ticket(id) ON DELETE CASCADE, sla_id TEXT NOT NULL REFERENCES helpdesk_sla(id), company_id TEXT NOT NULL REFERENCES companies(company_id), response_due TEXT, resolution_due TEXT, response_at TEXT, resolution_at TEXT, breached INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(ticket_id, sla_id)) STRICT;
    CREATE TABLE IF NOT EXISTS field_service_order (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), ticket_id TEXT REFERENCES helpdesk_ticket(id), partner_id TEXT REFERENCES partner_master(id), state TEXT NOT NULL DEFAULT 'draft', scheduled_date TEXT, technician_id TEXT, notes TEXT, created_at TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS field_service_part (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(company_id), order_id TEXT NOT NULL REFERENCES field_service_order(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES product_master(id), qty REAL NOT NULL, stock_move_id TEXT REFERENCES stock_move(id), issued_at TEXT) STRICT;
  `); },
  down(db) { db.exec('DROP TABLE IF EXISTS field_service_part; DROP TABLE IF EXISTS field_service_order; DROP TABLE IF EXISTS helpdesk_ticket_sla; DROP TABLE IF EXISTS helpdesk_sla; DROP TABLE IF EXISTS helpdesk_ticket; DROP TABLE IF EXISTS project_contract_line; DROP TABLE IF EXISTS project_timesheet; DROP TABLE IF EXISTS project_milestone; DROP TABLE IF EXISTS project_task_dependency; DROP TABLE IF EXISTS project_task; DROP TABLE IF EXISTS project_phase; DROP TABLE IF EXISTS project_project;'); }
};
