// ============================================================================
// Octagon Commercial — Workflow v2 stepper UI (P0.10)
// Pattern from erp-research/nocobase-main/docs/docs/en/workflow/ and
// octagon-erp/modules/automation-engine.js, re-expressed for vanilla JS.
// ============================================================================
(function (window, document) {
  'use strict';
  window.OX = window.OX || {};
  const api = '/api/x/workflows';
  const esc = value => String(value == null ? '' : value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const toast = (message, type) => window.showToast ? window.showToast(message, type || 'success') : window.alert(message);
  async function request(path, options) { const response = await fetch(api + path, { headers: { 'Content-Type': 'application/json' }, ...options }); const payload = await response.json(); if (!payload.success) throw new Error(payload.error || 'تعذر تنفيذ العملية'); return payload.data; }
  const types = { condition: 'شرط', 'update-record': 'تحديث سجل', 'create-record': 'إنشاء سجل', 'request-approval': 'طلب موافقة', notify: 'إشعار', webhook: 'Webhook' };
  function defaultNode(type) { return { id: `step_${Date.now()}`, type, label: types[type], config: type === 'notify' ? { role: 'sales', title: 'إشعار من سير العمل', body: '{{record.name}}' } : type === 'condition' ? { path: 'record.status', operator: 'eq', value: 'new' } : type === 'request-approval' ? { entity: '{{record.entity}}', record_id: '{{record.id}}', approver_role: 'manager' } : { entity: '', values: {} } }; }
  function nodeCard(node, index) { return `<article class="ox-workflow-step" data-step="${index}"><span class="ox-workflow-step__number">${index + 1}</span><div><strong>${esc(node.label || types[node.type])}</strong><small>${esc(types[node.type] || node.type)}</small></div><div class="ox-workflow-step__actions"><button type="button" data-move="up" aria-label="تحريك للأعلى">↑</button><button type="button" data-move="down" aria-label="تحريك للأسفل">↓</button><button type="button" data-remove="${index}" aria-label="حذف الخطوة">×</button></div></article>`; }
  function render(host, state) {
    const wf = state.workflow;
    host.dir = 'rtl';
    host.innerHTML = `<section class="ox-workflow" aria-label="منشئ سير العمل"><header class="ox-workflow__header"><div><h2>منشئ سير العمل</h2><p>خطوات متسلسلة قابلة للتدقيق — لا تعدّل الرواتب أو الدوام أو بيانات الموظفين.</p></div><button type="button" class="btn-primary" data-save>حفظ سير العمل</button></header><div class="ox-workflow__layout"><form class="ox-workflow__form"><label>اسم سير العمل<input name="name" value="${esc(wf.name || '')}" placeholder="مثال: إشعار مبيعات للعميل المحتمل الجديد"></label><label>نوع المحفّز<select name="trigger_type"><option value="record" ${wf.trigger?.type === 'record' ? 'selected' : ''}>إنشاء أو تحديث سجل</option><option value="schedule" ${wf.trigger?.type === 'schedule' ? 'selected' : ''}>مجدول</option><option value="manual" ${wf.trigger?.type === 'manual' ? 'selected' : ''}>يدوي</option></select></label><label>الكيان<input name="entity" value="${esc(wf.trigger?.entity || '')}" placeholder="crm_lead"></label><label>حدث السجل<select name="event"><option value="created">تم الإنشاء</option><option value="updated">تم التحديث</option><option value="created_or_updated">الإنشاء أو التحديث</option></select></label><label>فاصل التشغيل بالدقائق<input name="every_minutes" type="number" min="1" value="${esc(wf.trigger?.every_minutes || 60)}"></label><label class="ox-workflow__active"><input name="active" type="checkbox" ${wf.active !== false ? 'checked' : ''}> مفعّل</label></form><section class="ox-workflow__steps"><div class="ox-workflow__steps-head"><h3>الخطوات</h3><select data-add-type><option value="">إضافة خطوة…</option>${Object.entries(types).map(([type, label]) => `<option value="${type}">${label}</option>`).join('')}</select></div><div class="ox-workflow__step-list">${(wf.nodes || []).map(nodeCard).join('') || '<p class="ox-workflow__empty">أضف خطوة لتكوين سير العمل.</p>'}</div><label>إعدادات الخطوة المحددة (JSON)<textarea data-config rows="10" placeholder='{"role":"sales","title":"..."}'>${state.selected == null ? '' : esc(JSON.stringify(wf.nodes[state.selected]?.config || {}, null, 2))}</textarea></label><div class="ox-workflow__run"><button type="button" data-run ${wf.id ? '' : 'disabled'}>تشغيل يدوي آمن</button><button type="button" data-runs ${wf.id ? '' : 'disabled'}>سجل التشغيل</button></div><pre data-run-log class="ox-workflow__log"></pre></section></div></section>`;
    const event = host.querySelector('[name=event]'); event.value = wf.trigger?.event || 'created';
    host.querySelector('[data-add-type]').onchange = e => { const type = e.target.value; if (!type) return; wf.nodes = wf.nodes || []; wf.nodes.push(defaultNode(type)); state.selected = wf.nodes.length - 1; render(host, state); };
    host.querySelectorAll('[data-step]').forEach(card => card.onclick = event => { const index = Number(card.dataset.step); if (event.target.dataset.remove !== undefined) { wf.nodes.splice(index, 1); state.selected = null; render(host, state); return; } if (event.target.dataset.move) { const next = event.target.dataset.move === 'up' ? index - 1 : index + 1; if (wf.nodes[next]) [wf.nodes[index], wf.nodes[next]] = [wf.nodes[next], wf.nodes[index]]; state.selected = next; render(host, state); return; } state.selected = index; render(host, state); });
    host.querySelector('[data-config]').onchange = e => { if (state.selected == null) return; try { wf.nodes[state.selected].config = JSON.parse(e.target.value || '{}'); toast('تم حفظ إعدادات الخطوة مؤقتاً'); } catch (_) { toast('صيغة JSON غير صحيحة', 'error'); } };
    host.querySelector('[data-save]').onclick = async () => { const form = host.querySelector('form'); const values = new FormData(form); wf.name = values.get('name'); wf.active = values.get('active') === 'on'; wf.trigger = { ...(wf.trigger || {}), type: values.get('trigger_type'), entity: values.get('entity'), event: values.get('event'), every_minutes: Number(values.get('every_minutes') || 60) }; try { state.workflow = wf.id ? await request(`/update/${encodeURIComponent(wf.id)}`, { method: 'PATCH', body: JSON.stringify(wf) }) : await request('/create', { method: 'POST', body: JSON.stringify(wf) }); toast('تم حفظ سير العمل'); render(host, state); } catch (error) { toast(error.message, 'error'); } };
    host.querySelector('[data-run]').onclick = async () => { try { const run = await request(`/run/${encodeURIComponent(wf.id)}`, { method: 'POST', body: JSON.stringify({}) }); host.querySelector('[data-run-log]').textContent = JSON.stringify(run.logs, null, 2); toast(run.status === 'completed' ? 'اكتمل التشغيل' : 'انتهى التشغيل مع خطأ', run.status === 'completed' ? 'success' : 'error'); } catch (error) { toast(error.message, 'error'); } };
    host.querySelector('[data-runs]').onclick = async () => { try { host.querySelector('[data-run-log]').textContent = JSON.stringify(await request(`/runs/${encodeURIComponent(wf.id)}`), null, 2); } catch (error) { toast(error.message, 'error'); } };
  }
  window.OX.workflow = { async mount(host, workflow) { if (!host) throw new Error('Workflow host is required'); const state = { workflow: workflow || { name: '', active: true, trigger: { type: 'record', event: 'created', every_minutes: 60 }, nodes: [] }, selected: null }; render(host, state); return state; }, list: () => request('/list') };
})(window, document);
