// clean-room; behavior modeled on OCTAGON_VNEXT_MASTER_ROADMAP.md (proprietary self, not copied)
'use strict';

const stock = require('../../stock/stock-engine');
const infra = require('../r3-infra');
const { id, now, money, asDate, within, fail, ensureCompany, tableExists, withImmediateTransaction, idempotencyScope, rememberIdempotency, publish, recordWrite, location, product, issueNumber, approvalContract, approvedOverride } = infra;

function resolveRoute(db, companyId, input, userId, runtime) { const rule=db.prepare('SELECT * FROM stock_route_rule WHERE company_id=? AND active=1 AND (? IS NULL OR source_location_id IS NULL OR source_location_id=?) AND (? IS NULL OR dest_location_id IS NULL OR dest_location_id=?) ORDER BY sequence LIMIT 1').get(companyId,input.source_location_id||null,input.source_location_id||null,input.destination_location_id||null,input.destination_location_id||null); const row={id:id('route'),company_id:companyId,demand_ref:String(input.demand_ref||id('demand')),route_id:rule?.route_id||input.route_id||null,rule_id:rule?.id||null,source_location_id:rule?.source_location_id||input.source_location_id||null,destination_location_id:rule?.dest_location_id||input.destination_location_id||null,operation_type_id:rule?.operation_type_id||input.operation_type_id||null,state:'resolved',created_at:now()}; db.prepare('INSERT INTO stock_route_resolution(id,company_id,demand_ref,route_id,rule_id,source_location_id,destination_location_id,operation_type_id,state,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(...Object.values(row)); recordWrite(db,runtime,companyId,'stock_route_resolution',row.id,'resolved',userId,null,row,'warehouse'); return row; }

function createReorderRequest(db, companyId, input, userId, runtime) { const rule=db.prepare('SELECT * FROM stock_reorder_rule WHERE id=? AND company_id=?').get(input.reorder_rule_id,companyId); if(!rule) throw fail('reorder rule is outside company scope',403,'COMPANY_SCOPE_DENIED'); const current=Number(db.prepare('SELECT COALESCE(qty,0) qty FROM bin WHERE company_id=? AND product_id=? AND location_id=?').get(companyId,rule.product_id,rule.location_id)?.qty||0); const demand=Math.max(0,Number(rule.max_qty)-current); if(demand<=0&&!input.force) return {state:'not_required',current}; const row={id:id('reorder'),company_id:companyId,reorder_rule_id:rule.id,product_id:rule.product_id,demand_qty:Math.ceil(demand/Number(rule.multiple_qty||1))*Number(rule.multiple_qty||1),supply_ref:input.supply_ref||null,state:'draft',created_at:now()}; db.prepare('INSERT INTO stock_reorder_request(id,company_id,reorder_rule_id,product_id,demand_qty,supply_ref,state,created_at) VALUES(?,?,?,?,?,?,?,?)').run(...Object.values(row)); recordWrite(db,runtime,companyId,'stock_reorder_request',row.id,'created',userId,null,row,'warehouse'); return row; }

function putaway(db, companyId, input, userId, runtime) { const rule=db.prepare('SELECT * FROM stock_putaway_rule WHERE company_id=? AND active=1 AND warehouse_id=? AND (? IS NULL OR product_id=?) ORDER BY priority LIMIT 1').get(companyId,input.warehouse_id,input.product_id||null,input.product_id||null); if(!rule) throw fail('putaway rule is missing',404); const move=stock.createStockMove(db,companyId,{product_id:input.product_id,qty:Number(input.qty),from_location_id:input.source_location_id||rule.source_location_id,to_location_id:rule.destination_location_id,warehouse_id:rule.warehouse_id,currency:input.currency||'IQD',voucher_ref:input.voucher_ref||`PUT-${id('ref')}`}); const posted=stock.postStockMove(db,companyId,move.id,userId||'system',{rate:input.rate}); recordWrite(db,runtime,companyId,'stock_putaway_rule',rule.id,'applied',userId,null,{move_id:move.id,posted},'warehouse'); return {move_id:move.id,posted}; }

function pickPackShip(db, companyId, input, userId, runtime) { const pick=db.prepare('SELECT * FROM stock_pick WHERE id=? AND company_id=?').get(input.pick_id,companyId); if(!pick) throw fail('pick is outside company scope',403,'COMPANY_SCOPE_DENIED'); if(pick.state==='shipped') return pick; const destination=location(db,companyId,input.destination_type||'customer',input.destination_location_id); const result=withImmediateTransaction(db,()=>{const lines=db.prepare('SELECT * FROM stock_pick_line WHERE pick_id=? AND company_id=?').all(pick.id,companyId); const moves=[]; for(const line of lines){const requested=(input.lines||[]).find(item=>item.pick_line_id===line.id); const qty=Number(requested?.qty ?? (Number(line.picked_qty)>0?line.picked_qty:line.qty)); if(!(qty>0)||qty>Number(line.qty)) throw fail('picked quantity exceeds demand',409); const source=location(db,companyId,'internal',requested?.source_location_id||line.location_id); const voucher=`PICK-${pick.id}-${line.id}`; let posted=db.prepare("SELECT id,fiscal_doc_id FROM stock_move WHERE company_id=? AND voucher_ref=? AND state='done'").get(companyId,voucher); if(!posted){const move=stock.createStockMove(db,companyId,{product_id:line.product_id,qty,from_location_id:source.location_id,to_location_id:destination.location_id,warehouse_id:source.warehouse_id,currency:input.currency||'IQD',voucher_ref:voucher}); posted=stock.postStockMove(db,companyId,move.id,userId||'system',{batch_number:requested?.batch_number||line.batch_number,serial_number:requested?.serial_number||line.serial_number});} db.prepare('UPDATE stock_pick_line SET picked_qty=?,packed_qty=? WHERE id=?').run(qty,qty,line.id); moves.push({pick_line_id:line.id,move_id:posted.id||posted.moveId||null}); } db.prepare('UPDATE stock_pick SET state=?,packed_at=COALESCE(packed_at,?),shipped_at=? WHERE id=? AND company_id=?').run('shipped',now(),now(),pick.id,companyId); const row=db.prepare('SELECT * FROM stock_pick WHERE id=?').get(pick.id); recordWrite(db,runtime,companyId,'stock_pick',pick.id,'shipped',userId,null,{pick_id:pick.id,moves},'warehouse'); return row;}); return result; }

function cycleCountApprove(db, companyId, input, userId, runtime) { const count=db.prepare('SELECT * FROM stock_cycle_count WHERE id=? AND company_id=?').get(input.count_id,companyId); if(!count) throw fail('cycle count is outside company scope',403,'COMPANY_SCOPE_DENIED'); const approvalRow=approvalContract.getApprovedApproval(db,{id:input.approval_ref,companyId,tenantId:companyId,entity:'stock_cycle_count',recordId:count.id,action:'cycle_count_approve'}); if(!approvalRow) throw fail('canonical cycle-count approval is required',409,'APPROVAL_REQUIRED'); const requestedBy=String(approvalRow.requester_id||approvalRow.requester||''); if(!requestedBy||requestedBy===userId) throw fail('cycle-count approval maker-checker separation is required',403,'MAKER_CHECKER_REQUIRED'); const approval={id:approvalRow.id,company_id:companyId,count_id:count.id,requested_by:requestedBy,approved_by:userId,state:'approved',created_at:now(),decided_at:now()}; db.prepare('INSERT INTO stock_cycle_approval(id,company_id,count_id,requested_by,approved_by,state,created_at,decided_at) VALUES(?,?,?,?,?,?,?,?)').run(...Object.values(approval)); const lines=db.prepare('SELECT * FROM stock_cycle_count_line WHERE count_id=? AND company_id=?').all(count.id,companyId); const adjustments=[]; for(const line of lines){const current=Number(line.counted_qty); if(!Number.isFinite(current)) continue; const rate=Number(db.prepare('SELECT standard_cost FROM product_master WHERE id=? AND company_id=?').get(line.product_id,companyId)?.standard_cost||0); const adj=stock.postInventoryAdjustment(db,companyId,{id:id('adj'),location_id:count.location_id,product_id:line.product_id,counted_qty:current,counted_rate:rate,reason:`cycle-count:${count.id}`,authorized_by:userId,authorization_ref:approval.id,posting_date:asDate(input.posting_date)},userId); db.prepare('UPDATE stock_cycle_count_line SET variance=?,adjustment_id=? WHERE id=?').run(current-Number(line.expected_qty||0),adj.adjustmentId,line.id); adjustments.push(adj); } db.prepare('UPDATE stock_cycle_count SET state=?,approved_by=? WHERE id=?').run('approved',userId,count.id); recordWrite(db,runtime,companyId,'stock_cycle_count',count.id,'approved',userId,null,{adjustments},'warehouse'); return {approval,adjustments}; }

module.exports = {
  resolveRoute: infra.atomicCommand(resolveRoute),
  createReorderRequest: infra.atomicCommand(createReorderRequest),
  putaway: infra.atomicCommand(putaway),
  pickPackShip: infra.atomicCommand(pickPackShip),
  cycleCountApprove: infra.atomicCommand(cycleCountApprove),
  _internal: { resolveRoute, createReorderRequest, putaway, pickPackShip, cycleCountApprove },
};
