// clean-room; behavior modeled on OCTAGON_VNEXT_MASTER_ROADMAP.md (proprietary self, not copied)
// R3 online-first commercial workbench.
'use strict';
(function () {
  const company = document.getElementById('r3Company'); const state = document.getElementById('r3Connectivity'); const table = document.getElementById('r3Table'); const title = document.getElementById('r3PanelTitle'); const busy = document.getElementById('r3Busy');
  const labels = { products: 'المنتجات', quotes: 'المبيعات', 'purchase-orders': 'المشتريات', reservations: 'المخزون', boms: 'التصنيع', projects: 'الخدمات والدعم' }; let selected = 'products';
  const headers = () => ({ 'X-Company-Id': company.value.trim(), Accept: 'application/json' });
  async function request(path, options = {}) { const response = await fetch(path, { ...options, headers: { ...headers(), ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok || body.success === false) throw new Error(body.error || `HTTP ${response.status}`); return body.data; }
  function escapeHtml(value) { return String(value ?? '—').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function renderRows(rows) { if (!Array.isArray(rows) || !rows.length) { table.innerHTML = '<p class="empty">لا توجد سجلات بعد</p>'; return; } const keys = [...new Set(rows.flatMap(row => Object.keys(row)))].filter(key => !['company_id', 'created_at', 'created_by'].includes(key)).slice(0, 6); table.innerHTML = `<table><thead><tr>${keys.map(key => `<th>${key}</th>`).join('')}</tr></thead><tbody>${rows.slice(0, 30).map(row => `<tr>${keys.map(key => `<td>${escapeHtml(row[key])}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
  async function loadResource() { title.textContent = labels[selected] || selected; busy.textContent = '...'; try { renderRows(await request(`/api/x/r3/${selected}`)); busy.textContent = ''; } catch (error) { table.innerHTML = `<p class="error">${escapeHtml(error.message)}</p>`; busy.textContent = ''; } }
  async function refreshSnapshot() { state.dataset.state = 'connecting'; state.textContent = 'جاري الاتصال'; busy.textContent = '...'; try { const snapshot = await request('/api/x/r3/snapshot'); state.dataset.state = 'connected'; state.textContent = 'متصل'; Object.entries(snapshot.counts || {}).forEach(([key, value]) => { const node = document.querySelector(`[data-count="${key}"]`); if (node) node.textContent = value; }); await loadResource(); } catch (error) { state.dataset.state = 'offline'; state.textContent = 'غير متاح'; busy.textContent = error.message; table.innerHTML = `<p class="error">${escapeHtml(error.message)}</p>`; } }
  async function createProduct() { try { await request('/api/x/r3/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: `R3-${Date.now()}`, name: 'منتج تجريبي', product_type: 'goods' }) }); await refreshSnapshot(); } catch (error) { busy.textContent = error.message; } }
  document.querySelectorAll('.tab').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(item => item.classList.remove('active')); button.classList.add('active'); selected = button.dataset.resource; loadResource(); }));
  document.getElementById('r3Refresh').addEventListener('click', refreshSnapshot); document.getElementById('r3CreateProduct').addEventListener('click', createProduct); company.addEventListener('change', refreshSnapshot); refreshSnapshot();
}());
